name: helpus
description: Pedido de ajuda em um toque para pessoas com deficiência em eventos, com localização do GPS no WhatsApp.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.0
  mobile_scanner: ^7.0.0
  quick_actions: ^1.1.0
  shared_preferences: ^2.5.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/dados/
